import type { Metadata } from "next";
// import localFont from "next/font/local";
import "@/css/globals.css";
import MainPage from "./MainPage";

// const cooperHewitt = localFont({
//   src: [
//     {
//       path: './fonts/CooperHewitt-Thin.otf',
//       weight: '200',
//       style: 'normal',
//     },
//     {
//       path: './fonts/CooperHewitt-ThinItalic.otf',
//       weight: '200',
//       style: 'italic',
//     },
//     {
//       path: './fonts/CooperHewitt-Book.otf',
//       weight: '400',
//       style: 'normal',
//     },
//     {
//       path: './fonts/CooperHewitt-BookItalic.otf',
//       weight: '400',
//       style: 'italic',
//     },
//     {
//       path: './fonts/CooperHewitt-Medium.otf',
//       weight: '500',
//       style: 'normal',
//     },
//     {
//       path: './fonts/CooperHewitt-MediumItalic.otf',
//       weight: '500',
//       style: 'italic',
//     },
//     {
//       path: './fonts/CooperHewitt-Bold.otf',
//       weight: '700',
//       style: 'normal',
//     }
//   ]
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
    <html lang="en">
      <body>
        <MainPage>
          {children}
        </MainPage>
      </body>
    </html>
  );
}
